"""Target-generated training data for DFlash draft training.

The upstream DFlash recipe (arxiv:2602.06036) constructs its training
set from "responses generated by the target model for better target
alignment" — not ground-truth dataset text. Empirically the difference
is decisive for greedy-verification acceptance: a draft trained on
ground-truth ultrachat text reached ~0.4% acceptance on Qwen3-0.6B,
while the identical pipeline on target-greedy sequences works. The
intuition: the draft's job at inference time is to predict what the
*target* will say, and ground-truth text is an off-policy proxy whose
per-position argmax routinely disagrees with the target's.

This module provides that data path:

- ``safe_rope_patch``: context manager working around an mlx 0.31.x
  Metal bug where ``mx.fast.rope`` returns corrupt values for batch
  rows >= 1 when called with B > 1 at L == 1 (the batched single-token
  decode shape). Folding the batch dim into the heads dim is exact
  (RoPE rotates along the position axis only) and sidesteps the broken
  kernel path.
- ``iter_dataset_prompts``: stream chat-templated prompt token lists
  from a HuggingFace dataset (ultrachat-style ``prompt`` field or the
  first user message of ``messages``), with the same synthetic-prompt
  fallback as ``training_data.py``.
- ``generate_training_sequences``: batched greedy generation with
  exact-length prompt grouping (uniform-length rows need no padding or
  attention-mask plumbing).
- ``cycle_training_batches``: infinite epoch-cycling iterator yielding
  ``(input_ids, pivot_lo)`` batches for the trainer, where ``pivot_lo``
  is the batch's max prompt length — restricting training windows to
  the response region, matching upstream's response-anchor sampling.
"""

from __future__ import annotations

import logging
import random
from collections import defaultdict
from collections.abc import Iterator
from contextlib import contextmanager
from typing import Any

import mlx.core as mx
from mlx_lm.models.cache import make_prompt_cache

from olmlx.engine.dflash.training_data import (
    _FALLBACK_PROMPTS,
    DEFAULT_DATASET,
    DEFAULT_DATASET_SPLIT,
    _stream_hf_dataset,
)

logger = logging.getLogger(__name__)


@contextmanager
def safe_rope_patch() -> Iterator[None]:
    """Work around mlx 0.31.x ``mx.fast.rope`` corrupting batch rows >= 1
    for B > 1, L == 1 inputs (the batched decode shape).

    Folds the batch dim into the heads dim before the kernel call —
    exact because RoPE only rotates along the position axis (-2). Only
    the buggy shape is redirected; prefill (L > 1) and unbatched calls
    go straight through. The patch is process-global while active, so
    hold it only around the generation loop.
    """
    orig = mx.fast.rope

    def _folded(x: mx.array, dims: int, *args: Any, **kwargs: Any) -> mx.array:
        if getattr(x, "ndim", 0) == 4 and x.shape[0] > 1 and x.shape[2] == 1:
            B, H, L, D = x.shape
            out = orig(x.reshape(1, B * H, L, D), dims, *args, **kwargs)
            return out.reshape(B, H, L, D)
        return orig(x, dims, *args, **kwargs)

    mx.fast.rope = _folded
    try:
        yield
    finally:
        mx.fast.rope = orig


def iter_dataset_prompts(
    tokenizer: Any,
    *,
    dataset: str = DEFAULT_DATASET,
    split: str = DEFAULT_DATASET_SPLIT,
    max_prompt_tokens: int = 120,
) -> Iterator[list[int]]:
    """Yield chat-templated prompt token lists for self-generation.

    Recognizes the ultrachat-style ``prompt`` string field and the
    ``messages`` list shape (first user turn). Prompts longer than
    ``max_prompt_tokens`` after templating are skipped — long prompts
    slow generation down without adding response-distribution coverage.
    Falls back to the synthetic prompts when ``datasets`` is missing,
    mirroring ``stream_training_batches``.
    """

    def _render(prompt: str) -> list[int] | None:
        try:
            text = tokenizer.apply_chat_template(
                [{"role": "user", "content": prompt}],
                tokenize=False,
                add_generation_prompt=True,
            )
            ids = tokenizer.encode(text, add_special_tokens=False)
        except Exception:  # noqa: BLE001 — skip unrenderable examples
            return None
        if len(ids) > max_prompt_tokens:
            return None
        return list(ids)

    stream = _stream_hf_dataset(dataset, split)
    if stream is not None:
        for example in stream:
            prompt = example.get("prompt")
            if not isinstance(prompt, str) or not prompt:
                messages = example.get("messages")
                if isinstance(messages, list):
                    user = next(
                        (
                            m.get("content")
                            for m in messages
                            if isinstance(m, dict) and m.get("role") == "user"
                        ),
                        None,
                    )
                    prompt = user if isinstance(user, str) else None
            if not prompt:
                continue
            ids = _render(prompt)
            if ids is not None:
                yield ids
        return

    while True:  # synthetic fallback, cycled; caller caps via num_seqs
        for prompt in _FALLBACK_PROMPTS:
            ids = _render(prompt)
            if ids is not None:
                yield ids


def generate_training_sequences(
    target: Any,
    tokenizer: Any,
    *,
    prompts: Iterator[list[int]],
    num_seqs: int,
    max_new: int,
    group_size: int = 16,
    progress_callback: Any = None,
) -> list[tuple[list[int], int]]:
    """Greedy-generate ``num_seqs`` training sequences with the target.

    Prompts are grouped by exact token length so each generation batch
    is rectangular without padding (right-padding would corrupt
    attention for the shorter rows; left-padding needs mask plumbing
    mlx-lm's cache path doesn't have). Returns ``(sequence, prompt_len)``
    pairs where ``sequence`` is prompt + generated tokens, ending at the
    first EOS (inclusive) or after ``max_new`` tokens.
    """
    if num_seqs < 1:
        raise ValueError(f"num_seqs must be >= 1, got {num_seqs}")
    if max_new < 1:
        raise ValueError(f"max_new must be >= 1, got {max_new}")
    eos_ids = set(
        tokenizer.eos_token_ids
        if getattr(tokenizer, "eos_token_ids", None)
        else [tokenizer.eos_token_id]
    )

    out: list[tuple[list[int], int]] = []

    def _run_group(rows: list[list[int]]) -> None:
        B = len(rows)
        cache = make_prompt_cache(target)
        logits = target(mx.array(rows), cache=cache)
        logits = getattr(logits, "logits", logits)
        cur = mx.argmax(logits[:, -1:, :], axis=-1)
        gens: list[list[int]] = [[] for _ in range(B)]
        done = [False] * B
        for _ in range(max_new):
            for b, t in enumerate(cur[:, 0].tolist()):
                if not done[b]:
                    gens[b].append(int(t))
                    if int(t) in eos_ids:
                        done[b] = True
            if all(done):
                break
            logits = target(cur, cache=cache)
            logits = getattr(logits, "logits", logits)
            cur = mx.argmax(logits, axis=-1)
        for b in range(B):
            out.append((rows[b] + gens[b], len(rows[b])))
        if progress_callback:
            progress_callback(
                f"Self-generating training data {len(out)}/{num_seqs}",
                min(len(out) / num_seqs, 1.0),
            )

    groups: dict[int, list[list[int]]] = defaultdict(list)
    with safe_rope_patch():
        for ids in prompts:
            if len(out) >= num_seqs:
                break
            groups[len(ids)].append(ids)
            if len(groups[len(ids)]) >= group_size:
                _run_group(groups.pop(len(ids)))
        # Flush leftovers (largest groups first) until the quota is met.
        for length in sorted(groups, key=lambda k: -len(groups[k])):
            if len(out) >= num_seqs:
                break
            rows = groups[length]
            while rows and len(out) < num_seqs:
                _run_group(rows[:group_size])
                rows = rows[group_size:]

    if len(out) < num_seqs:
        logger.warning(
            "Self-generation produced %d of the requested %d sequences "
            "(prompt stream exhausted).",
            len(out),
            num_seqs,
        )
    return out[:num_seqs]


def cycle_training_batches(
    sequences: list[tuple[list[int], int]],
    batch_size: int,
    *,
    pad_token_id: int,
    block_size: int,
    seed: int = 0,
) -> Iterator[tuple[mx.array, int]]:
    """Yield ``(input_ids, pivot_lo)`` batches forever, reshuffling each epoch.

    Two per-sequence filters apply before bucketing:

    - the global floor ``len >= 2 * block_size + 1`` (the trainer's
      minimum window size), and
    - the prompt-aware floor ``len >= prompt_len + block_size + 1`` — a
      long-prompt/short-response sequence can pass the global floor yet
      never yield a valid window once the per-batch ``pivot_lo``
      (response-region restriction) applies; worse, it drags the whole
      bucket's ``pivot_lo`` up so ``_select_pivots`` silently skips the
      batch for every row in it.

    The survivors are sorted by length and packed into fixed same-size
    buckets (padding waste stays minimal and every row in a batch shares
    a similar pivot range). A partial tail bucket is topped up by
    replicating its own rows (same convention as
    ``stream_training_batches``) rather than dropped — otherwise up to
    ``batch_size - 1`` generated sequences would silently never be
    trained on. ``pivot_lo`` is the max prompt length within the batch
    so the trainer can restrict windows to the response region. The
    iterator is infinite — the training loop's ``steps`` budget is the
    termination condition, which is how multi-epoch training falls out
    naturally.
    """
    usable = [
        (s, plen)
        for s, plen in sequences
        if len(s) >= 2 * block_size + 1 and len(s) >= plen + block_size + 1
    ]
    if not usable:
        raise ValueError(
            f"No self-generated sequences usable for block_size="
            f"{block_size}: each needs at least 2*block_size + 1 = "
            f"{2 * block_size + 1} tokens AND block_size + 1 = "
            f"{block_size + 1} tokens past its prompt. Increase "
            "--selfgen-max-new or check the prompt stream."
        )
    usable.sort(key=lambda sp: len(sp[0]))
    buckets: list[tuple[list[list[int]], int]] = []
    for i in range(0, len(usable), batch_size):
        rows = usable[i : i + batch_size]
        # Top up a partial tail bucket (also the fewer-sequences-than-
        # one-batch case) by cycling its own rows.
        orig = len(rows)
        while len(rows) < batch_size:
            rows.append(rows[len(rows) % orig])
        m = max(len(s) for s, _ in rows)
        padded = [s + [pad_token_id] * (m - len(s)) for s, _ in rows]
        # Clamp the bucket's pivot floor so the pivot range can never be
        # empty: the per-sequence filter guarantees each row clears its
        # OWN prompt by block_size + 1 tokens, but the bucket floor is
        # the max prompt length across rows, and sorted-by-length
        # bucketing can still pair a long-prompt row with a shorter row
        # when the length distribution has gaps — ``_select_pivots``
        # would then skip the whole batch. Clamping trades that silent
        # skip for a few windows that may overlap the long-prompt row's
        # prompt region (the pre-pivot_lo behavior for that row alone).
        shortest = min(len(s) for s, _ in rows)
        pivot_lo = min(max(plen for _, plen in rows), shortest - block_size - 1)
        buckets.append((padded, pivot_lo))
    rng = random.Random(seed)
    while True:
        rng.shuffle(buckets)
        for padded, pivot_lo in buckets:
            yield mx.array(padded), pivot_lo
