"""Tests for DFlash self-generated training data (upstream recipe).

The upstream DFlash recipe trains the draft on responses GENERATED BY
THE TARGET MODEL ("for better target alignment"), not ground-truth
dataset text. Empirically the difference is decisive: ground-truth
training produced ~0.4% acceptance; the same pipeline on target-greedy
sequences works. ``engine/dflash/selfgen.py`` provides that data path.
"""

from __future__ import annotations

import json

import mlx.core as mx
import mlx.nn as nn
import pytest

from olmlx.engine.dflash.selfgen import (
    cycle_training_batches,
    generate_training_sequences,
    safe_rope_patch,
)
from olmlx.engine.dflash.prepare import (
    _select_pivot,
    _select_pivots,
    prepare_dflash_draft,
)

from tests.test_dflash_prepare import (  # reuse the existing fakes
    _mock_target_loader,
    _write_target_config,
)


# ---------------------------------------------------------------------------
# safe_rope_patch
# ---------------------------------------------------------------------------


class TestSafeRopePatch:
    def test_batched_decode_rope_matches_per_row_reference(self):
        """mlx 0.31.1's mx.fast.rope corrupts rows >= 1 for B > 1, L == 1.
        Under the patch, the batched call must match per-row results."""
        B, H, L, D = 4, 8, 1, 64
        mx.random.seed(0)
        rows = [mx.random.normal((1, H, L, D)).astype(mx.bfloat16) for _ in range(B)]
        x = mx.concatenate(rows, axis=0)
        kwargs = dict(traditional=False, base=1e6, scale=1.0, offset=11)
        with safe_rope_patch():
            batched = mx.fast.rope(x, D, **kwargs)
            refs = [mx.fast.rope(r, D, **kwargs) for r in rows]
        mx.eval(batched, *refs)
        for b in range(B):
            assert float(mx.abs(batched[b] - refs[b][0]).max().item()) == 0.0

    def test_patch_is_reverted_on_exit(self):
        orig = mx.fast.rope
        with safe_rope_patch():
            assert mx.fast.rope is not orig
        assert mx.fast.rope is orig

    def test_patch_reverted_on_exception(self):
        orig = mx.fast.rope
        with pytest.raises(RuntimeError):
            with safe_rope_patch():
                raise RuntimeError("boom")
        assert mx.fast.rope is orig


# ---------------------------------------------------------------------------
# generate_training_sequences
# ---------------------------------------------------------------------------


class _ScriptedTarget(nn.Module):
    """Greedy chain is deterministic: next = (last + 3) % vocab.

    Tracks forward calls so tests can assert exact-length grouping
    (every prefill batch must carry rows of one uniform length).
    """

    def __init__(self, vocab: int = 64):
        super().__init__()
        self.vocab = vocab
        self.prefill_shapes: list[tuple[int, int]] = []

    def __call__(self, input_ids, cache=None):
        B, L = input_ids.shape
        if L > 1:
            self.prefill_shapes.append((B, L))
        nxt = (input_ids + 3) % self.vocab
        eye = mx.eye(self.vocab)
        return eye[nxt.reshape(-1)].reshape(B, L, self.vocab)


class _GenTokenizer:
    pad_token_id = 0
    eos_token_id = 1


class TestGenerateTrainingSequences:
    def test_greedy_chain_and_prompt_len(self):
        target = _ScriptedTarget()
        prompts = [[10, 11, 12], [20, 21], [30, 31, 32]]
        seqs = generate_training_sequences(
            _ScriptedTargetWrapper(target),
            _GenTokenizer(),
            prompts=iter(prompts),
            num_seqs=3,
            max_new=4,
            group_size=2,
        )
        by_plen = {tuple(s[:plen]): (s, plen) for s, plen in seqs}
        s, plen = by_plen[(10, 11, 12)]
        assert plen == 3
        # next = (last + 3) % 64 chain: 12 -> 15 -> 18 -> 21 -> 24
        assert s == [10, 11, 12, 15, 18, 21, 24]

    def test_eos_stops_row(self):
        target = _ScriptedTarget()
        # chain from 62: (62+3)%64=1 == eos -> generation stops after eos
        seqs = generate_training_sequences(
            _ScriptedTargetWrapper(target),
            _GenTokenizer(),
            prompts=iter([[60, 62]]),
            num_seqs=1,
            max_new=8,
            group_size=1,
        )
        s, plen = seqs[0]
        assert s == [60, 62, 1]  # eos kept, nothing after

    def test_exact_length_grouping(self):
        target = _ScriptedTarget()
        prompts = [[10, 11], [12, 13, 14], [15, 16], [17, 18, 19]]
        generate_training_sequences(
            _ScriptedTargetWrapper(target),
            _GenTokenizer(),
            prompts=iter(prompts),
            num_seqs=4,
            max_new=2,
            group_size=2,
        )
        # every prefill batch must be over uniform-length rows
        assert all(L in (2, 3) for _, L in target.prefill_shapes)


class _ScriptedTargetWrapper(nn.Module):
    """Gives _ScriptedTarget the .layers attribute prepare-side code expects."""

    def __init__(self, inner: _ScriptedTarget):
        super().__init__()
        self.inner = inner
        self.layers: list = []

    def __call__(self, input_ids, cache=None):
        return self.inner(input_ids, cache=cache)


# ---------------------------------------------------------------------------
# cycle_training_batches
# ---------------------------------------------------------------------------


class TestCycleTrainingBatches:
    def _seqs(self):
        # (sequence, prompt_len) of assorted lengths
        return [
            (list(range(2, 42)), 5),
            (list(range(2, 44)), 7),
            (list(range(2, 46)), 6),
            (list(range(2, 48)), 4),
            (list(range(2, 80)), 9),
            (list(range(2, 82)), 8),
        ]

    def test_yields_padded_batches_with_pivot_lo(self):
        it = cycle_training_batches(
            self._seqs(), batch_size=2, pad_token_id=0, block_size=4
        )
        ids, pivot_lo = next(it)
        assert ids.shape[0] == 2
        # pivot_lo is the max prompt length within the batch
        assert isinstance(pivot_lo, int) and pivot_lo >= 4
        # rows padded to the in-batch max with pad_token_id
        assert ids.shape[1] == max(int((ids[r] != 0).sum().item()) for r in range(2))

    def test_filters_short_sequences(self):
        seqs = [(list(range(2, 8)), 2)] + self._seqs()
        it = cycle_training_batches(seqs, batch_size=2, pad_token_id=0, block_size=4)
        for _ in range(6):
            ids, _ = next(it)
            assert ids.shape[1] >= 9  # 2*block_size + 1

    def test_filters_long_prompt_short_response_sequences(self):
        # 50 tokens total but a 48-token prompt: passes the global
        # 2*block_size+1 length floor yet can never yield a window once
        # pivot_lo applies (needs len >= plen + block_size + 1 = 53).
        # Including it would drag the whole bucket's pivot_lo up and get
        # the batch silently skipped by _select_pivots.
        bad = (list(range(2, 52)), 48)
        it = cycle_training_batches(
            [bad] + self._seqs(), batch_size=2, pad_token_id=0, block_size=4
        )
        for _ in range(6):  # two epochs of the 3 remaining buckets
            ids, pivot_lo = next(it)
            assert pivot_lo <= 9  # the bad row's plen=48 never appears
            assert int((ids[0] != 0).sum().item()) != 50

    def test_pivot_lo_clamped_to_keep_pivot_range_nonempty(self):
        # Each row clears its OWN prompt (len >= plen + block_size + 1),
        # but a length-distribution gap can pair a long-prompt row with
        # a shorter row in one bucket: max(plen)=80 > 60 - 4 - 1, so an
        # unclamped pivot_lo would empty the pivot range and skip the
        # batch. The bucket floor is clamped to shortest - block_size - 1.
        seqs = [
            (list(range(2, 102)), 80),  # len 100, plen 80 (80+5 <= 100)
            (list(range(2, 62)), 5),  # len 60, plen 5
        ]
        it = cycle_training_batches(seqs, batch_size=2, pad_token_id=0, block_size=4)
        ids, pivot_lo = next(it)
        assert pivot_lo == 60 - 4 - 1
        # the clamped floor leaves a valid pivot range for _select_pivots
        assert _select_pivots(ids, 0, 4, 2, min_pivot=pivot_lo) is not None

    def test_cycles_forever(self):
        it = cycle_training_batches(
            self._seqs(), batch_size=2, pad_token_id=0, block_size=4
        )
        got = [next(it) for _ in range(10)]  # > 3 batches/epoch
        assert len(got) == 10

    def test_partial_tail_batch_is_replicated_not_dropped(self):
        # 5 usable sequences, batch_size 2 -> 3 buckets/epoch; the tail
        # bucket is topped up by replication instead of dropping seq 5.
        seqs = self._seqs()[:5]
        it = cycle_training_batches(seqs, batch_size=2, pad_token_id=0, block_size=4)
        rows_seen: set[int] = set()
        for _ in range(3):  # one epoch
            ids, _ = next(it)
            for r in range(ids.shape[0]):
                rows_seen.add(int((ids[r] != 0).sum().item()))
        # every distinct sequence length appears -> nothing was dropped
        assert rows_seen == {len(s) for s, _ in seqs}

    def test_single_sequence_fills_batch_by_replication(self):
        seqs = [(list(range(2, 42)), 5)]
        it = cycle_training_batches(seqs, batch_size=4, pad_token_id=0, block_size=4)
        ids, pivot_lo = next(it)
        assert ids.shape == (4, 40)
        assert pivot_lo == 5


# ---------------------------------------------------------------------------
# min_pivot plumbing
# ---------------------------------------------------------------------------


class TestMinPivot:
    def test_select_pivot_respects_min_pivot(self):
        ids = mx.array([[5] * 100])
        for _ in range(20):
            p = _select_pivot(ids, 0, 8, min_pivot=40)
            assert p is not None and 40 <= p <= 100 - 8 - 1

    def test_select_pivot_returns_none_when_no_room(self):
        ids = mx.array([[5] * 30])
        assert _select_pivot(ids, 0, 8, min_pivot=25) is None

    def test_select_pivots_respects_min_pivot(self):
        ids = mx.array([[5] * 200])
        for _ in range(10):
            ps = _select_pivots(ids, 0, 8, 4, min_pivot=90)
            assert ps is not None
            assert all(p >= 90 for p in ps)

    def test_legacy_behavior_unchanged_without_min_pivot(self):
        import random

        ids = mx.array([[5] * 100])
        random.seed(42)
        a = _select_pivot(ids, 0, 8)
        random.seed(42)
        b = _select_pivot(ids, 0, 8, min_pivot=0)
        assert a == b


# ---------------------------------------------------------------------------
# prepare integration
# ---------------------------------------------------------------------------


class TestPrepareSelfGenerate:
    def test_pivot_lo_tuple_batches_thread_min_pivot(self, tmp_path, monkeypatch):
        from olmlx.engine.dflash import prepare as prepare_mod

        _write_target_config(tmp_path, vocab_size=64, hidden_size=16)
        seen: list[int] = []
        orig = prepare_mod._select_pivots

        def spy(input_ids, pad, bs, k, min_pivot=0):
            seen.append(min_pivot)
            return orig(input_ids, pad, bs, k, min_pivot=min_pivot)

        monkeypatch.setattr(prepare_mod, "_select_pivots", spy)

        def batches():
            while True:
                ids = (mx.arange(64, dtype=mx.int32)[None, :] % 62) + 2
                yield (mx.concatenate([ids] * 2, axis=0), 12)

        prepare_dflash_draft(
            model_path=tmp_path,
            steps=2,
            batch_size=2,
            seq_len=64,
            block_size=4,
            num_hidden_layers=1,
            num_target_layers=2,
            output_dir=tmp_path / "out",
            _target_loader=_mock_target_loader(64, 16, 4),
            _batch_iterator=batches(),
            train_windows_per_step=2,
        )
        assert seen and all(m == 12 for m in seen)

    def test_self_generate_end_to_end(self, tmp_path):
        _write_target_config(tmp_path, vocab_size=64, hidden_size=16)
        prompts = [[(7 * i + j) % 60 + 2 for j in range(6)] for i in range(8)]
        out = prepare_dflash_draft(
            model_path=tmp_path,
            steps=2,
            batch_size=2,
            seq_len=64,
            block_size=4,
            num_hidden_layers=1,
            num_target_layers=2,
            output_dir=tmp_path / "out",
            _target_loader=_mock_target_loader(64, 16, 4),
            self_generate=True,
            selfgen_num_seqs=8,
            selfgen_max_new=24,
            _prompt_iter=iter(prompts),
        )
        assert (out / "config.json").exists()
        cfg = json.loads((out / "config.json").read_text())
        assert cfg["dflash_config"]["mask_token_id"] == 0  # pad id

    def test_self_generate_no_pad_tokenizer_uses_padded_pivot_path(
        self, tmp_path, monkeypatch
    ):
        """A tokenizer with neither pad nor eos (explicit mask_token_id)
        leaves ``pad_for_pivot`` None — but the selfgen batcher right-pads
        with 0, so the loop must still use the pad-aware ``_select_pivots``
        (the inline unpadded sampler would let pivots land inside padding
        and train the draft on pad tokens unmasked)."""
        from olmlx.engine.dflash import prepare as prepare_mod
        from tests.test_dflash_prepare import _MockTokenizer, _Target

        _write_target_config(tmp_path, vocab_size=64, hidden_size=16)

        class _NoPadTokenizer(_MockTokenizer):
            pad_token_id = None
            eos_token_id = None

        def loader(_path):
            return _Target(64, 16, 4), _NoPadTokenizer(vocab_size=64, seq_len=64)

        calls: list[int] = []
        orig = prepare_mod._select_pivots

        def spy(input_ids, pad, bs, k, min_pivot=0):
            calls.append(pad)
            return orig(input_ids, pad, bs, k, min_pivot=min_pivot)

        monkeypatch.setattr(prepare_mod, "_select_pivots", spy)

        # Mixed-length prompts force real right-padding in the buckets.
        prompts = [[(7 * i + j) % 60 + 2 for j in range(4 + (i % 3))] for i in range(8)]
        prepare_dflash_draft(
            model_path=tmp_path,
            steps=2,
            batch_size=2,
            seq_len=64,
            block_size=4,
            num_hidden_layers=1,
            num_target_layers=2,
            output_dir=tmp_path / "out",
            _target_loader=loader,
            self_generate=True,
            selfgen_num_seqs=8,
            selfgen_max_new=24,
            mask_token_id=63,
            _prompt_iter=iter(prompts),
        )
        # the pad-aware selector ran, with the batcher's pad id (0)
        assert calls and all(p == 0 for p in calls)

    def test_self_generate_rejects_precomputed(self, tmp_path):
        _write_target_config(tmp_path, vocab_size=64, hidden_size=16)
        with pytest.raises(ValueError, match="self_generate.*use_precomputed"):
            prepare_dflash_draft(
                model_path=tmp_path,
                steps=1,
                self_generate=True,
                use_precomputed=tmp_path / "shards",
                _target_loader=_mock_target_loader(64, 16, 4),
            )
