"""Generate target-aligned DFlash training data.

Mirrors the upstream DFlash recipe: training sequences are responses
GENERATED BY THE TARGET MODEL (greedy), not ground-truth dataset text.
Prompts come from ultrachat; generation is batched greedy with
exact-length prompt grouping (no padding needed inside a group).

Output: JSONL with one {"ids": [...]} per sequence (prompt + response,
post-EOS positions replaced by pad_token_id).
"""

from __future__ import annotations

import argparse
import json
import time
from collections import defaultdict
from pathlib import Path

import mlx.core as mx
from mlx_lm import load
from mlx_lm.models.cache import make_prompt_cache

# mlx 0.31.1: mx.fast.rope CORRUPTS rows >= 1 when called with batch > 1
# at L == 1 (decode shape) — minimal repro in scripts/dflash_diagnose
# work; rows 1..B-1 of batched greedy decode go degenerate. Fold the
# batch dim into the heads dim (RoPE rotates along axis -2 only, so the
# fold is exact) before calling the original kernel.
_orig_rope = mx.fast.rope


def _safe_rope(x, dims, *args, **kwargs):
    if x.ndim == 4 and x.shape[0] > 1:
        B, H, L, D = x.shape
        out = _orig_rope(x.reshape(1, B * H, L, D), dims, *args, **kwargs)
        return out.reshape(B, H, L, D)
    return _orig_rope(x, dims, *args, **kwargs)


mx.fast.rope = _safe_rope


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--num-seqs", type=int, default=1500)
    ap.add_argument("--max-new", type=int, default=640)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--max-prompt-tokens", type=int, default=120)
    args = ap.parse_args()

    target, tok = load(str(Path(args.target).expanduser()))
    pad_id = tok.pad_token_id if tok.pad_token_id is not None else tok.eos_token_id
    eos_ids = set(
        tok.eos_token_ids if hasattr(tok, "eos_token_ids") else [tok.eos_token_id]
    )
    print(f"pad={pad_id} eos={sorted(eos_ids)}")

    import datasets as ds

    stream = ds.load_dataset(
        "HuggingFaceH4/ultrachat_200k", split="train_sft", streaming=True
    )

    # Group chat-templated prompts by exact token length so each batch
    # needs no padding.
    groups: dict[int, list[list[int]]] = defaultdict(list)
    out_path = Path(args.out)
    out_f = out_path.open("w")
    written = 0
    t0 = time.time()

    def run_batch(rows: list[list[int]]) -> None:
        nonlocal written
        B = len(rows)
        ids = mx.array(rows)
        cache = make_prompt_cache(target)
        logits = target(ids, cache=cache)
        logits = getattr(logits, "logits", logits)
        cur = mx.argmax(logits[:, -1:, :], axis=-1)  # (B, 1)
        outs: list[list[int]] = [[] for _ in range(B)]
        done = [False] * B
        for _ in range(args.max_new):
            cur_l = cur[:, 0].tolist()
            for b in range(B):
                if not done[b]:
                    outs[b].append(int(cur_l[b]))
                    if int(cur_l[b]) in eos_ids:
                        done[b] = True
            if all(done):
                break
            logits = target(cur, cache=cache)
            logits = getattr(logits, "logits", logits)
            cur = mx.argmax(logits, axis=-1)
        for b in range(B):
            seq = rows[b] + outs[b]
            out_f.write(json.dumps({"ids": seq}) + "\n")
            written += 1
        out_f.flush()
        rate = written / max(time.time() - t0, 1)
        print(
            f"  {written}/{args.num_seqs} seqs "
            f"({rate:.1f} seq/s, batch={B}, resp~{len(outs[0])})",
            flush=True,
        )

    for ex in stream:
        if written >= args.num_seqs:
            break
        prompt = ex.get("prompt")
        if not prompt or not isinstance(prompt, str):
            continue
        text = tok.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=False,
            add_generation_prompt=True,
        )
        ids = tok.encode(text, add_special_tokens=False)
        if len(ids) > args.max_prompt_tokens:
            continue
        groups[len(ids)].append(ids)
        if len(groups[len(ids)]) >= args.batch:
            run_batch(groups.pop(len(ids)))

    # Flush remaining groups (largest first) until quota.
    for length in sorted(groups, key=lambda k: -len(groups[k])):
        if written >= args.num_seqs:
            break
        rows = groups[length]
        while rows and written < args.num_seqs:
            run_batch(rows[: args.batch])
            rows = rows[args.batch :]

    out_f.close()
    print(f"wrote {written} sequences to {out_path}")


if __name__ == "__main__":
    main()
